Стилизация
htmlacademy-adaptive/2263217-sedona-28 pull request #2
Opened 2023-05-18 17:00 UTC by komradlew

---
:mortar_board: [Стилизация](https://up.htmlacademy.ru/adaptive/28/user/2263217/tasks/7)

2023-05-18 21:52 UTC, pavel-niukalo requested changes
Плюс как уже отписался в дискорде не забудь поправить ошибки линтера

2023-05-18 21:52 UTC, pavel-niukalo commented on source/sass/blocks/catalog/photo-item.scss
> +.photo__title,
Файл называется `photo-item` - вот для этого блока и его элементов/модификаторо (`photo-item__...`) здесь и должны быть стили.

`photo__title` (и другие) - элемент блока `photo` и соответственно должны быть описаны в файле `photo.scss`

2023-05-18 21:52 UTC, pavel-niukalo commented on source/sass/blocks/catalog/photo-item.scss
> +  font-family: "PT Sans", sans-serif;
Можно прописать `font-family` один раз в `body` и дальше не дублировать

2023-05-18 21:52 UTC, pavel-niukalo commented on source/sass/blocks/catalog/photo-list.scss
На пустые файлы линтер тоже будет ругаться, так что можешь пока заглушки сюда закинуть

2023-05-18 21:52 UTC, pavel-niukalo commented on source/sass/blocks/form/feedback-container.scss
> +.feedback__title {
Аналогично - файл для блока `feedback-container` и его составляющих. Для блока `feedback` - свой файл. Тут возможно ты пересмотришь именование и вообще например от блока `feedback-container` откажешься

2023-05-18 21:52 UTC, pavel-niukalo commented on source/sass/blocks/form/feedback.scss
> +.button-submit {
`button-submit` - в свой файл

2023-05-18 21:52 UTC, pavel-niukalo commented on source/sass/blocks/index/benefits-item.scss
> +.benefits__title {
+1 не совпадают блок и название файла

2023-05-18 21:52 UTC, pavel-niukalo commented on source/sass/blocks/index/benefits-list.scss
> +.benefits__list {
+1

Возможно я понял - у тебя для элементов созданы файлы (`benefits-item.scss`, `benefits-list.scss`). Файлы у нас должны быть только для БЭМ-блоков. Например, создаем файл `benefits.scss` и в нем описываем, все что относится к этому блоку, и `benefits__list` и `benefits__item` и тд

2023-05-18 21:52 UTC, pavel-niukalo commented on source/sass/blocks/index/intro-wrapper-image.scss
> +  background: #81B3D2 url("../../../img/hero-mobile.jpg") no-repeat;
По поводу путей до картинок. Относительно этого файла - ок, написано в целом верно. Но! Стоит помнить, что браузер у нас препроцессорный код не понимает, а понимает только css. Соответственно, для этого у нас сборкой все и собирается в `style.CSS` (все что мы наподключали в `style.SCSS`). И соответственно, к странице у нас будет подключен обычный css. Вот от этого файла и нужно писать пути (поскольку по итогу они и будут применяться). А структура у нас такая:
```
/
|
|__style/
|____style.css
|__fonts/
|____...
|__img/
|____...
|__index.html
...
```

Соответственно, относительно `style.css` путь должен быть как `url('../img/hero-mobile.jpg')`

2023-05-18 21:52 UTC, pavel-niukalo commented on source/sass/blocks/index/intro-wrapper.scss
> +.intro__title {
В общем стоит везде проверить на соответствие названия файла и блока, описываемого в нем

2023-05-18 21:52 UTC, pavel-niukalo commented on source/sass/style.scss
> +}
Для `font-face` лучше сделать отдельный файл и подключить его первым (чтобы у использующих свойст уже был доступ к шрифтам)

2023-05-18 21:52 UTC, pavel-niukalo commented on source/sass/style.scss
> +}
Это тоже в отдельный файл. В style.scss у нас должны остаться только подключения

И вот как раз в `page__body` можно прописать общий `font-family` (и не забудь указать веб-безопасный шрифт, в критериях есть примеры)

2023-05-18 21:52 UTC, pavel-niukalo commented on source/sass/style.scss
> +.visually-hidden {
Тоже в отдельный файл

2023-05-18 21:52 UTC, pavel-niukalo requested changes
Плюс как уже отписался в дискорде не забудь поправить ошибки линтера

2023-05-21 12:11 UTC, komradlew commented on source/sass/blocks/form/feedback-container.scss
> +.feedback__title {
тогда в будущих домашках переименую, посмотрю?
пока перекинул в feedback

2023-05-22 20:32 UTC, pavel-niukalo approved these changes

2023-05-22 20:32 UTC, merged